### ISSUE TITLE
Doesn't match Etherscan or MEW

### ISSUE THREAD

**Issue by NoahMarconi** [eth-button/blockie-picker#2]
Are you using different algorithms to produce the blockies?

**Comment by NoahMarconi** [comment]
I guess the follow up question is, if you're using the same algorithm as mew, I assume this is a bug on the canvas display side. Is there a way for me to debug in the console to get the correct key?

**Comment by eth-button** [comment]
Do you have a sample address that is generating a different result?  I think this issue technically applies to [`lib-blockies`](https://github.com/eth-button/lib-blockies), but we can track it here.

**Comment by eth-button** [comment]
@NoahMarconi I ended up realizing that this was due to me passing the checksum addresses (mixed case) to the blockie generator, and have fixed it upstream.

Let me know if you still see mismatches!
